# Generated by Django 5.2.8 on 2025-11-28 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postattachment_delete_posattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(verbose_name='Контент коммента')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания коммента')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Коммент')),
            ],
        ),
    ]
