# Generated by Django 5.2.8 on 2026-01-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Content_en',
            field=models.TextField(null=True, verbose_name='Контент поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='Content_kk',
            field=models.TextField(null=True, verbose_name='Контент поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='Content_ru',
            field=models.TextField(null=True, verbose_name='Контент поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
    ]
