# Generated by Django 5.2.8 on 2026-01-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_content_en_post_content_kk_post_content_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Content_kk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_kk',
        ),
    ]
